name: app-clinica-ami

services:
  postgres:
    image: postgres:16-alpine
    container_name: ami-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ami_postgres_data:/var/lib/postgresql/data
      - ./database/migrations/001_especialidades_medicos.sql:/docker-entrypoint-initdb.d/001_especialidades_medicos.sql:ro
      - ./database/migrations/002_modulos_clinicos.sql:/docker-entrypoint-initdb.d/002_modulos_clinicos.sql:ro
      - ./database/migrations/003_seguridad_facturacion_inventario.sql:/docker-entrypoint-initdb.d/003_seguridad_facturacion_inventario.sql:ro
      - ./database/migrations/004_ajustes_y_modulos_publicos.sql:/docker-entrypoint-initdb.d/004_ajustes_y_modulos_publicos.sql:ro
      - ./database/migrations/005_indices_listados_crud.sql:/docker-entrypoint-initdb.d/005_indices_listados_crud.sql:ro
      - ./database/migrations/006_indices_administracion_erp.sql:/docker-entrypoint-initdb.d/006_indices_administracion_erp.sql:ro
      - ./database/migrations/007_pacientes_agenda_expediente.sql:/docker-entrypoint-initdb.d/007_pacientes_agenda_expediente.sql:ro
      - ./database/migrations/008_recetas_procedimientos_laboratorio.sql:/docker-entrypoint-initdb.d/008_recetas_procedimientos_laboratorio.sql:ro
      - ./database/migrations/009_auditoria_trazabilidad.sql:/docker-entrypoint-initdb.d/009_auditoria_trazabilidad.sql:ro
      - ./database/migrations/010_especialidades_expediente_psicologico.sql:/docker-entrypoint-initdb.d/010_especialidades_expediente_psicologico.sql:ro
      - ./database/migrations/011_administracion_contenido_web.sql:/docker-entrypoint-initdb.d/011_administracion_contenido_web.sql:ro
      - ./database/migrations/012_facturacion_caja_inventario.sql:/docker-entrypoint-initdb.d/012_facturacion_caja_inventario.sql:ro
      - ./database/migrations/013_archivos_consentimientos.sql:/docker-entrypoint-initdb.d/013_archivos_consentimientos.sql:ro
      - ./database/seed.sql:/docker-entrypoint-initdb.d/900_seed.sql:ro
      - ./database/tests:/database-tests:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

volumes:
  ami_postgres_data:
    name: ami_postgres_data
