"use client";

import type { StatusInput, WebAnnouncementInput, WebAnnouncementItem, WebContentOptions } from "@ami/contracts";
import { zodResolver } from "@hookform/resolvers/zod";
import type { ColumnDef } from "@tanstack/react-table";
import { ImageIcon, LoaderCircle } from "lucide-react";
import { useEffect, useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { apiRequest } from "../../lib/api-client";
import { confirmDiscardChanges, showError, showSuccess } from "../../lib/alerts";
import { applyApiFormErrors } from "../administration/form-api-error";
import { RecordActions } from "../administration/record-actions";
import { ResourcePanel } from "../administration/resource-panel";
import { useResourceList } from "../administration/use-resource-list";
import { FormField, FormSection } from "../crud/form-field";
import { DetailModal, FormModal, MediaPreviewModal } from "../crud/modal";
import { StatusBadge } from "../crud/status-badge";
import { formatPublicationDate, mediaUrl, PublicationBadge } from "./web-content-shared";

const schema = z.object({ title: z.string().trim().min(2).max(150), description: z.string().trim().max(5000), styleId: z.number().int().min(1, "Seleccione un estilo."), promotionId: z.number().int().min(0), startDate: z.string().min(1), endDate: z.string().min(1), imageUrl: z.string().trim().max(500).refine((value) => !value || mediaUrl.test(value), "Use una ruta local o una dirección http/https.") }).refine((value) => value.endDate >= value.startDate, { path: ["endDate"], message: "Debe ser igual o posterior a la fecha inicial." });
type AnnouncementForm = z.infer<typeof schema>; const TODAY = new Date().toISOString().slice(0, 10); const EMPTY: AnnouncementForm = { title: "", description: "", styleId: 0, promotionId: 0, startDate: TODAY, endDate: TODAY, imageUrl: "" };

export function AnnouncementsManager({ canWrite }: Readonly<{ canWrite: boolean }>) {
  const list = useResourceList<WebAnnouncementItem>({ endpoint: "/web-content/announcements", defaultSort: "startDate", defaultSortDescending: true });
  const [options, setOptions] = useState<WebContentOptions | null>(null); const [editing, setEditing] = useState<WebAnnouncementItem | null>(null); const [formOpen, setFormOpen] = useState(false); const [detail, setDetail] = useState<WebAnnouncementItem | null>(null); const [preview, setPreview] = useState<WebAnnouncementItem | null>(null); const [pending, setPending] = useState<number | null>(null);
  const form = useForm<AnnouncementForm>({ resolver: zodResolver(schema), defaultValues: EMPTY });
  useEffect(() => { let active = true; apiRequest<WebContentOptions>("/web-content/options").then((value) => { if (active) setOptions(value); }).catch(() => { if (active) void showError("No se cargaron las opciones", "Revise los estilos y promociones antes de crear anuncios."); }); return () => { active = false; }; }, []);
  function create() { setEditing(null); form.reset({ ...EMPTY, styleId: options?.styles.find((item) => item.active)?.id ?? 0 }); setFormOpen(true); } function edit(row: WebAnnouncementItem) { setEditing(row); form.reset({ title: row.title, description: row.description ?? "", styleId: row.style.id, promotionId: row.promotion?.id ?? 0, startDate: row.startDate, endDate: row.endDate, imageUrl: row.imageUrl ?? "" }); setFormOpen(true); }
  async function close() { if (form.formState.isDirty && !(await confirmDiscardChanges())) return; setFormOpen(false); }
  const save = form.handleSubmit(async (values) => { const payload: WebAnnouncementInput = { title: values.title, styleId: values.styleId, promotionId: values.promotionId || null, startDate: values.startDate, endDate: values.endDate, ...(values.description ? { description: values.description } : {}), ...(values.imageUrl ? { imageUrl: values.imageUrl } : {}) }; try { await apiRequest<WebAnnouncementItem>(editing ? `/web-content/announcements/${editing.id}` : "/web-content/announcements", { method: editing ? "PATCH" : "POST", body: JSON.stringify(payload) }); setFormOpen(false); list.reload(); void showSuccess(editing ? "Anuncio actualizado" : "Anuncio creado como borrador", editing ? "La configuración quedó guardada." : "Actívelo cuando el contenido y su vigencia estén listos."); } catch (reason) { const error = applyApiFormErrors(reason, form.setError); void showError("No se guardó el anuncio", error.message); } });
  async function status(row: WebAnnouncementItem, active: boolean) { setPending(row.id); try { await apiRequest<WebAnnouncementItem>(`/web-content/announcements/${row.id}/status`, { method: "PATCH", body: JSON.stringify({ active } satisfies StatusInput) }); list.reload(); void showSuccess(active ? "Anuncio activado" : "Anuncio desactivado", "La vigencia define cuándo será visible."); } catch (reason) { const error = applyApiFormErrors(reason, form.setError); void showError("No se cambió el estado", error.message); } finally { setPending(null); } }
  const columns: ColumnDef<WebAnnouncementItem>[] = [
    { id: "title", accessorKey: "title", header: "Anuncio", cell: ({ row }) => <div className="table-module-cell"><strong>{row.original.title}</strong><span>{row.original.style.name}</span></div> },
    { id: "startDate", accessorKey: "startDate", header: "Inicio", cell: ({ row }) => formatPublicationDate(row.original.startDate) }, { id: "endDate", accessorKey: "endDate", header: "Fin", cell: ({ row }) => formatPublicationDate(row.original.endDate) },
    { id: "publication", header: "Publicación", enableSorting: false, cell: ({ row }) => <PublicationBadge state={row.original.publicationState} /> },
    { id: "promotion", header: "Promoción", enableSorting: false, cell: ({ row }) => row.original.promotion?.title ?? <span className="table-muted">Sin vínculo</span> },
    { id: "actions", header: "Acciones", enableSorting: false, cell: ({ row }) => <div className="record-actions">{row.original.imageUrl && <button className="table-action-button" type="button" onClick={() => setPreview(row.original)}><ImageIcon aria-hidden="true" /> Imagen</button>}<RecordActions active={row.original.active} canWrite={canWrite} entityLabel={`el anuncio ${row.original.title}`} onDetail={() => setDetail(row.original)} onEdit={() => edit(row.original)} onStatus={(active) => status(row.original, active)} statusPending={pending === row.original.id} /></div> },
  ];
  return <><ResourcePanel canWrite={canWrite && Boolean(options?.styles.some((item) => item.active))} columns={columns} description="Administre anuncios y pop-ups, sus estilos, promociones vinculadas y fechas de publicación." emptyTitle="No hay anuncios" emptyDescription="Cree un estilo activo y luego registre el primer anuncio." getRowId={(row) => String(row.id)} list={list} onCreate={create} searchPlaceholder="Buscar anuncio, estilo o promoción" title="Anuncios y pop-ups" />
    <FormModal open={formOpen} onClose={() => { void close(); }} onSubmit={save} isSubmitting={form.formState.isSubmitting} submitLabel={editing ? "Guardar cambios" : "Crear borrador"} title={editing ? "Editar anuncio" : "Nuevo anuncio"} description={!options ? "Cargando catálogos…" : "El anuncio se crea desactivado para evitar una publicación accidental."}><FormSection title="Contenido"><FormField htmlFor="announcement-title" label="Título" required error={form.formState.errors.title?.message}><input {...form.register("title")} /></FormField><FormField htmlFor="announcement-description" label="Descripción" error={form.formState.errors.description?.message}><textarea {...form.register("description")} rows={4} /></FormField><FormField htmlFor="announcement-image" label="URL de imagen" error={form.formState.errors.imageUrl?.message}><input {...form.register("imageUrl")} placeholder="/MEDIA/anuncio.jpg" /></FormField></FormSection><FormSection title="Presentación y vigencia"><div className="crud-form-grid"><FormField htmlFor="announcement-style" label="Estilo" required error={form.formState.errors.styleId?.message}><select {...form.register("styleId", { valueAsNumber: true })} disabled={!options}><option value={0}>Seleccione un estilo</option>{options?.styles.map((item) => <option key={item.id} value={item.id} disabled={!item.active}>{item.label}{item.active ? "" : " · Inactivo"}</option>)}</select></FormField><FormField htmlFor="announcement-promotion" label="Promoción vinculada" error={form.formState.errors.promotionId?.message}><select {...form.register("promotionId", { valueAsNumber: true })} disabled={!options}><option value={0}>Sin promoción</option>{options?.promotions.map((item) => <option key={item.id} value={item.id}>{item.label}{item.active ? "" : " · Inactiva"}</option>)}</select></FormField><FormField htmlFor="announcement-start" label="Fecha inicial" required error={form.formState.errors.startDate?.message}><input {...form.register("startDate")} type="date" /></FormField><FormField htmlFor="announcement-end" label="Fecha final" required error={form.formState.errors.endDate?.message}><input {...form.register("endDate")} type="date" /></FormField></div></FormSection></FormModal>
    <DetailModal open={detail !== null} onClose={() => setDetail(null)} title="Detalle del anuncio" footer={<button className="button button-primary" type="button" onClick={() => setDetail(null)}>Cerrar</button>}>{detail ? <dl className="permission-detail-list"><div><dt>Título</dt><dd>{detail.title}</dd></div><div><dt>Estilo</dt><dd>{detail.style.name} · <StatusBadge active={detail.style.active} activeLabel="Activo" inactiveLabel="Inactivo" /></dd></div><div><dt>Promoción</dt><dd>{detail.promotion?.title || "Sin vínculo"}</dd></div><div><dt>Vigencia</dt><dd>{formatPublicationDate(detail.startDate)} — {formatPublicationDate(detail.endDate)}</dd></div><div><dt>Publicación</dt><dd><PublicationBadge state={detail.publicationState} /></dd></div></dl> : <LoaderCircle className="spin" />}</DetailModal>
    {preview?.imageUrl && <MediaPreviewModal open onClose={() => setPreview(null)} title={preview.title} kind="image" url={preview.imageUrl} />}</>;
}
